Class {
	#name : 'MLargeBoardStrategy',
	#superclass : 'MBoardSizeStrategy',
	#category : 'Myg-MineSweeper-Model',
	#package : 'Myg-MineSweeper',
	#tag : 'Model'
}

{ #category : 'accessing' }
MLargeBoardStrategy >> height [
    ^ 16
]

{ #category : 'accessing' }
MLargeBoardStrategy >> magnifierDefault [
    ^ 0.6
]

{ #category : 'accessing' }
MLargeBoardStrategy >> name [
    ^ '16x16'
]

{ #category : 'accessing' }
MLargeBoardStrategy >> width [
    ^ 16
]
