Class {
	#name : 'MMediumBoardStrategy',
	#superclass : 'MBoardSizeStrategy',
	#category : 'Myg-MineSweeper-Model',
	#package : 'Myg-MineSweeper',
	#tag : 'Model'
}

{ #category : 'accessing' }
MMediumBoardStrategy >> height [
    ^ 10
]

{ #category : 'accessing' }
MMediumBoardStrategy >> magnifierDefault [
    ^ 0.8
]

{ #category : 'accessing' }
MMediumBoardStrategy >> name [
    ^ '10x10'
]

{ #category : 'accessing' }
MMediumBoardStrategy >> width [
    ^ 10
]
