Class {
	#name : 'MSmallBoardStrategy',
	#superclass : 'MBoardSizeStrategy',
	#category : 'Myg-MineSweeper-Model',
	#package : 'Myg-MineSweeper',
	#tag : 'Model'
}

{ #category : 'accessing' }
MSmallBoardStrategy >> height [
    ^ 5
]

{ #category : 'accessing' }
MSmallBoardStrategy >> magnifierDefault [
    ^ 1
]

{ #category : 'accessing' }
MSmallBoardStrategy >> name [
    ^ '5x5'
]

{ #category : 'accessing' }
MSmallBoardStrategy >> width [
    ^ 5
]
