Class {
	#name : 'MVeryLargeBoardStrategy',
	#superclass : 'MBoardSizeStrategy',
	#category : 'Myg-MineSweeper-Model',
	#package : 'Myg-MineSweeper',
	#tag : 'Model'
}

{ #category : 'accessing' }
MVeryLargeBoardStrategy >> height [
    ^ 20
]

{ #category : 'accessing' }
MVeryLargeBoardStrategy >> magnifierDefault [
    ^ 0.5
]

{ #category : 'accessing' }
MVeryLargeBoardStrategy >> name [
    ^ '20x20'
]

{ #category : 'accessing' }
MVeryLargeBoardStrategy >> width [
    ^ 20
]
